@startuml Robot-man
class RobotMan
{
+saltar
+correr(movimiento)
+disparar
}
class Enemigo
{
+disparar
}
class Plataforma
class LocalArcade
class RobotmanJuego
{
    -Enemigo: _Enemigo_[4]
    -RobotMan
}
class Personaje
class Escenario
class Mapa
class Color
class Bala
class Arma
class Dificultad
class Animacion
class Movimiento
{
+salto()
+agachado()
+izquierda()
+derecha()
}
class Jugador 
class Nivel
class Musica
class Computadora

Computadora *--RobotmanJuego
RobotmanJuego *--Mapa
Mapa --|> Nivel
Mapa *-- Plataforma
Mapa *-- Musica
RobotmanJuego *-- Personaje
RobotMan --|> Personaje
RobotMan *-- Color
Enemigo --|> Personaje
Enemigo *-- Color
RobotmanJuego *-- Fantasma
LocalArcade *-- Computadora
Computadora *-- RobotmanJuego
Enemigo *-- Movimiento
Jugador o-- RobotMan
Nivel *-- Dificultad
Animacion o-- Movimiento
Escenario *-- Mapa
Arma *-- Bala
RobotMan *-- Arma
RobotmanJuego o-- RobotMan

@enduml